feat: add CLI version check in CI

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -24,6 +24,17 @@ jobs:
       - name: install holochain_cli_launch to make sure it compiles
         run: cargo build --release --bin hc-launch
 
+      - name: check that version string has been (manually) updated correctly
+        run: |
+          # This checks that the version string in ./crates/hc_launch/src-tauri-src/cli.rs has been (manually) set to the correct holochain version
+          hc_version_cli=$(./target/release/hc-launch --version | grep -oP '\(holochain \K[^)]+')
+          hc_version_cargo_toml=$(grep -E '^holochain_conductor_api' Cargo.toml | awk -F' = ' '{print $2}' | tr -d '"')
+
+          if [ "$hc_version_cli" != "$hc_version_cargo_toml" ]; then
+            echo "ERROR: The holochain version set in the verison string in ./crates/hc_launch/src-tauri-src/cli.rs does not match the holochain version in Cargo.toml."
+            exit 1
+          fi
+
   ci_pass:
     if: ${{ always() }}
     runs-on: "ubuntu-latest"
